# Generated by Django 5.2.3 on 2025-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='end_time',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='start_time',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='duration',
            field=models.CharField(),
        ),
    ]
