# Generated by Django 5.2.3 on 2025-07-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week_planner', '0002_taskmodel_end_time_taskmodel_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
